version: "3.8"

services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - "leela_audio_data:/var/lib/leela/data"

  database:
    image: postgres
    env_file:
      - .env
    ports:
      - "5442:5432"
    volumes:
      - "leela_postgres_data:/var/lib/postresql/data"

volumes:
  leela_postgres_data:
    driver: local

  leela_audio_data:
    driver: local
