"""empty message

Revision ID: 0455c06b4af7
Revises: fbb69bbd9312
Create Date: 2023-02-16 23:04:07.225894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0455c06b4af7'
down_revision = 'fbb69bbd9312'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.create_unique_constraint('one_text', ['text'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.drop_constraint('one_text', type_='unique')

    # ### end Alembic commands ###
