"""empty message

Revision ID: d072e7dec0c6
Revises: 0455c06b4af7
Create Date: 2023-02-19 17:52:59.447012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd072e7dec0c6'
down_revision = '0455c06b4af7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_transcript')
    with op.batch_alter_table('transcript', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.Enum('ENGLISH', 'SPANISH', name='transcriptlanguageenum'), server_default='ENGLISH', nullable=False))
        batch_op.create_unique_constraint('one_audio_id', ['audio_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcript', schema=None) as batch_op:
        batch_op.drop_constraint('one_audio_id', type_='unique')
        batch_op.drop_column('language')

    op.create_table('_alembic_tmp_transcript',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=11), nullable=False),
    sa.Column('audio_id', sa.INTEGER(), nullable=True),
    sa.Column('external_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('language', sa.VARCHAR(length=7), nullable=False),
    sa.ForeignKeyConstraint(['audio_id'], ['audio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audio_id', name='one_audio_id'),
    sa.UniqueConstraint('external_id', name='one_external_id')
    )
    # ### end Alembic commands ###
