name: dev-build-deploy
on: [push]

jobs:
  build_deploy:
    runs-on: self-hosted
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Make envfile
        run: echo "${{ secrets.ENV_FILE }}" > /home/gkrapivin/actions-runner/_work/leela/leela/.env
      - name: cat makefile
        run: docker-compose up --build -d
