name: dev-build-deploy
on: [push]

jobs:
  build_deploy:
    runs-on: self-hosted
    steps:
      - name: Make envfile
        run: |
          echo "${{ secrets.env_file }}" > .env
      - name: checkout repo
        uses: actions/checkout@v2
      - name: cat makefile
        run: docker-compose up -d
