name: dev-build-deploy
on:
  push:
    branches:
      - main

jobs:
  build_deploy:
    runs-on: self-hosted
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Make envfile
        run: echo "${{ secrets.ENV_FILE }}" > /home/gkrapivin/actions-runner/_work/leela/leela/.env
      - name: Make google-service-account-key
        run: echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT }}" | base64 -d > /home/gkrapivin/actions-runner/_work/leela/leela/key.json
      - name: cat makefile
        run: docker-compose up --build -d

